#### Laura Belén Rodríguez Rodríguez
#### 25-08-24

1. Del archivo de excel
* Calcula la Utilidad (Ingreso - Gasto)
* Encuentra el promedio de Gastos en los meses que la Utilidad fue negativa
* Encuentra los ingresos totales del año

In [11]:
import pandas as pd
datos = pd.read_excel("datosCT.xlsx")
datos

Unnamed: 0  Ingreso  Gasto
0        Enero     1340   1880
1      Febrero     2590   3130
2        Marzo     3570   2140
3        Abril     4450   3370
4         Mayo     1330   2990
5        Junio     1610   1970
6        Julio     1500   2230
7       Agosto     2270   1240
8   Septiembre     1910   1470
9      Octubre     2120   2280
10   Noviembre     3950   1870
11   Diciembre     1380   3140

In [73]:
datos.columns

Index(['Unnamed: 0', 'Ingreso', 'Gasto'], dtype='object')

In [101]:
datos['Utilidad'] = datos['Ingreso'] - datos['Gasto']
Utilidad

0     -540
1     -540
2     1430
3     1080
4    -1660
5     -360
6     -730
7     1030
8      440
9     -160
10    2080
11   -1760
dtype: int64

In [99]:
utilidad_negativa = datos[datos['Utilidad'] < 0] #para separar los meses que fueron negativos
promedio_negativo = utilidad_negativa['Gasto'].mean() #para devolver el valor promedio 
utilidad_negativa
promedio_negativo

2517.1428571428573

In [85]:
TotalIngreso = datos['Ingreso'].sum()
TotalIngreso 

28020

 2. Crea las siguientes estructuras usando numpy:

In [65]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [63]:
B = np.array([[1], [2]])
B

array([[1],
       [2]])

In [61]:
A @ B

array([[ 5],
       [11]])