Laura Rodriguez 09-09-24

Ejercicio 1.

Una carpintería local fabrica sillas, mesas, libreros y bases de cama. Hay dos empleados en esta carpintería: un empleado experimentado y un aprendiz. El aprendiz tarda aproximadamente 50% más tiempo que el carpintero experimentado en construir cualquier cosa, además de que tiene un desperdicio de alrededor de 20% de material. Los materiales y tiempos necesarios para construir algo se desglozan en la siguiente tabla:

Mesa = 3, 6

Silla = 1, 2

Libreros = 4, 5

Bases = 3, 5

Las mesas se venden en  9000, las sillas en  3000, los libreros en  10000, y las bases de cama en  9000. Suponiendo una jornada de 40 horas a la semana y que tienen 100 unidades de madera, ¿qué les conviene construir durante una semana para maximizar su ganancia?

* 
¿Cuántas horas trabaja cada quin?
  
* 
¿Cuánto material sesa?
  
* ?
¿Cuál se el ingreso total si se vende todo lo fabricado?

1. Identificar el criterio
   
Se busca maximizar la ganancia 

3. Variables de control
   
* Cantidad de mesas del empleado (x1)
* Cantidad de sillas del empleado (x2)
* Cantidad de libreros del empleado (x3)
* Cantidad de bases de cama del empleado (x4)
* Cantidad de mesas del aprendiz (y1)
* Cantidad de sillas del aprendiz (y2)
* Cantidad de libreros del aprendiz (y3)
* Cantidad de bases de cama del aprendiz (y4)
  
3. funcion de costo
   
  $ f(x1, x2, x3, x4, y1, y2, y3, y4) = 9000x1+ 9000y1 + 3000x2+3000y2 + 10000x3+10000y3 + 9000x4+ 9000y4 $

4. Restricciones

Tiempo experimentado

$ 3x1 + 1x2 + 4x3 + 3x4 \leq 40 $

Tiempo aprendiz 

$ 4.5y1 + 1.5y2 + 6y3 + 4.5y4 \leq 40 $

Material 

$ 6x1 + 7.2y1 + 2x2+ 2.4y2 + 5x3 + 6y3 + 5x4+ 6y4 \leq 100 $

$$ \min_{x1,x2,x3,x4,y1,y2,y3,y4} -9000x1-9000y1-3000x2-3000y2-10000x3-10000y3-9000x4-9000y4 $$
$$ \text {s.t.} $$
$$3x1+1x2+4x3+3x4 \leq 40$$
$$4.5y1+1.5y2+6y3+4.5y4 \leq 40$$
$$6x1+7.2y1+2x2+2.4y2+5x3+6y3+5x4+6y4 \leq 100$$
   


In [47]:
import scipy.optimize as opt
import numpy as np

Aub = np.array([
    [3,  0,  1,  0,  4, 0, 3, 0],
    [0, 4.5, 0, 1.5, 0, 6, 0, 4.5],
    [6, 7.2, 2, 2.4, 5, 6, 5, 6]
])

bub = np.array([
    40,
    40,
    100

])

c = np.array([
    -9000,
    -9000,
    -3000,
    -3000,
    -10000,
    -10000,
    -9000,
    -9000
])

sol= opt.linprog(c,Aub,bub,integrality=1) 
sol.fun

-176000.0

In [49]:
sol.x

array([ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00, -9.47390314e-15,
        9.00000000e+00,  2.00000000e+00,  1.00000000e+00,  6.00000000e+00])

In [51]:
Aub @ sol.x

array([ 40.,  39., 100.])

2. La carpintería recibió una orden  por 3 combos de mesa + 6 sillas.
* ¿Se puede cumplir la orden?
* Si sí, ¿qué es lo que tienen que fabricar en el resto del tiempo y con el resto del material para maximizar su ganancia?
* ¿Cuántas horas trabaja cada quién?
* 
¿Cuánto material seusa? 
*
¿Cuál es el nuevo ingreso tota

4. Restricciones extras
   
Mesas

$ x1+y1 \geq 3 $

Sillas

$ x2+y2 \geq 18 $

$$ \min_{x1,x2,x3,x4,y1,y2,y3,y4} -9000x1-9000y1-3000x2-3000y2-10000x3-10000y3-9000x4-9000y4 $$
$$ \text {s.t.} $$
$$3x1+1x2+4x3+3x4 \leq 40$$
$$4.5y1+1.5y2+6y3+4.5y4 \leq 40$$
$$6x1+7.2y1+2x2+2.4y2+5x3+6y3+5x4+6y4 \leq 100$$
$$ x1+y1 \geq 3 $$
$$ x2+y2 \geq 18 $$l?

In [55]:
import scipy.optimize as opt
import numpy as np


c = np.array([-9000, -9000, -3000, -3000, -10000, -10000, -9000, -9000])

Aub = np.array([
    [3, 0, 1, 0, 4, 0, 3, 0],     
    [0, 4.5, 0, 1.5, 0, 6, 0, 4.5], 
    [6, 7.2, 2, 2.4, 5, 6, 5, 6],
    [0, 0, -1, -1, 0, 0, 0, 0],
    [-1, -1, 0, 0, 0, 0, 0, 0] 
])

bub = np.array([
    40,
    40,
    100,
    -18,
    -3
])


sol = opt.linprog(c,Aub,bub,integrality=1) 
sol.fun  #la ganancia total


-161000.0

In [57]:
sol.x

array([ 3.,  0., 18.,  0.,  3.,  5.,  0.,  0.])

In [59]:
Aub @ sol.x

array([ 39.,  30.,  99., -18.,  -3.])