Laura Rodriguez 11-09-24

Una multinacional farmacéutica desea fabricar un compuesto nutritivo a base de dos productos A y B.  El producto A contiene  $30\%$ de proteínas,  un $1\%$ de grasas y un  $10\%$ de azúcares.  El producto B  contiene  un  $5\%$  de proteínas,  un  $7\%$ de grasas  y un  $10\%$  de  azúcares.

El compuesto debe de tener,  al menos, $25g$ de proteínas,  $6g$ de grasas y $30g$ de azúcares.  El coste del producto A es de $0.6$ u.m./g  y el de B es de $0.2$  u.m./g

Se desea encontrar la cantidad en gramos de cada producto para que el coste total sea mínimo.

Formular el problema de decidir cuánto hacer de cada producto como un problema de programación lineal.

1. Identificar el criterio
   
Encontrar la cantidad en gramos de productos en A y B para que sea el menor costo

3. Variables de control

* Cantidad de producto A x1
* Cantidad de producto B x2

3. funcion de costo
f(x1,x2) = 0.6x1 + 0.2x2

4. Restricciones
   
Proteínas

$ 0.30x1 + 0.05x2 \geq 25 $

Grasas

$ 0.01x1 + 0.07x2 \geq 6 $

Azúcares

$ 0.10x1 + 0.30x2 \geq 30 $

$$ \min_{x1,x2} 0.6x1 + 0.2x2 $$
$$ \text {s.t.} $$
$$ 0.30x1 + 0.05x2 \geq 25 $$
$$ 0.01x1 + 0.07x2 \geq 6 $$
$$ 0.10x1 + 0.10x2 \geq 30 $$

   

In [8]:
import numpy as np
import scipy.optimize as opt

c = np.array([0.6, 0.2])

Aub = np.array([
    [-0.30, -0.05], 
    [-0.01, -0.07],  
    [-0.10, -0.10]
   
])

bub = np.array([-25, -6, -30])

sol = opt.linprog(c, Aub, bub,integrality=1)
sol.fun #costo total mínimo 

76.00000000000001

In [10]:
sol.x

array([ 40., 260.])


Una  fábrica  de  carrocerías  de  automóviles  y camiones  tiene  dos naves. 

+ En  la nave A,  para  hacer  la  carrocería  de  un  camión,  se  invierten  siete  días-operario,  para  fabricar  la  de  un  coche  se  precisan dos días-operario.

+ En la nave B se invierten tres días operario tanto en carrocerías de camión como de coche. 

Por limitaciones de mano de obra y maquinaria, la nave A dispone de $300$ días operario, y la nave B de $270$ días-operario.

Si los beneficios que se obtienen por cada camión son de $600$ u.m y por  cada  automóvil  $200$ u.m,  ¿cuántas  unidades  de  cada  uno  se deben  producir  para maximizar las  ganancias? 

**Nota:** el problema $\max_{\boldsymbol{x}}\boldsymbol{g}(\boldsymbol{x})$ es equivalente a $\min_{\boldsymbol{x}}-\boldsymbol{g}(\boldsymbol{x})$.

1. Encontrar el criterio

Se busca determinar cuántas unidades de cada tipo de vehículo deben producirse para maximizar las ganancias, dadas las restricciones de tiempo disponible en las naves

2. Variables de control

* Camiones en nave A x1
* Autos en nave A x2
* Camiones en nave B y1
* Autos en nave B y2

3. función de costo

f(x1,x2,y1,y2) = 200x1 + 600x2 + 200y1 + 600y2

4. Restricciones

Nave A = 300 dias
Nave B = 270 

Nave A

$ 2x1 + 7y1 \leq 300 $

Nave B

$ 3x2 + 3y2 \leq 270$

$$ \min_{x1,x2,y1,y2} -200x1 - 600x2 - 200y1 - 600y2$$
$$ \text {s.t.} $$
$$ 2x1 + 7y1 \leq 300 $$
$$ 3x2 + 3y2 \leq 270 $$

   

In [22]:
import numpy as np
import scipy.optimize as opt

c = np.array([-200, -600, -200, -600])

Aub = np.array([
    [2, 0, 7, 0], 
    [0, 3, 0, 3]  
])

bub = np.array([300, 270])

sol = opt.linprog(c, Aub, bub,integrality=1)
sol.fun #costo total mínimo 

-84000.0

In [24]:
sol.x

array([150.,  90.,   0.,   0.])

**Actividad.** Mónica hace aretes y cadenitas de joyería. Es tan buena, que todo lo que hace lo vende.

Le toma 30 minutos hacer un par de aretes y una hora hacer una cadenita, y como Mónica también es estudihambre, solo dispone de 10 horas a la semana para hacer las joyas. Por otra parte, el material que compra solo le alcanza para hacer 15 unidades (el par de aretes cuenta como unidad) de joyas por semana.

La utilidad que le deja la venta de las joyas es $\$15$ en cada par de aretes y $\$20$ en cada cadenita.

¿Cuántos pares de aretes y cuántas cadenitas debería hacer Mónica para maximizar su utilidad?



1. Identificar criterio

Maximizar la utilidad que Mónica puede obtener al producir aretes y cadenitas, dadas las limitaciones de tiempo y material.

2. Variables de control
* Cantidad de pares de aretes x1
* Cantidad de cadenitas x2

3. Funcion de costo
f(x1,x2) = 15x1 + 20x2

4. Restricciones
   
Tiempo que dispone

$ 30x1 + 60x2 \leq 600 $  #tiempo en minutos, 10 horas = 600 minutos

Material que dispone 

$ x1 + x2 \leq 15 $

$$ \min_{x1,x2} 15x1 + 20x2 $$
$$ \text {s.t.} $$
$$ 30x1 + 60x2 \leq 600 $$
$$ x1 + x2 \leq 15 $$




In [32]:
import numpy as np
import scipy.optimize as opt

c = np.array([-15, -20])

Aub = np.array([
    [30, 60], 
    [1, 1]  
])

bub = np.array([600, 15])

sol = opt.linprog(c, Aub, bub,integrality=1)
sol.fun #costo total mínimo 

-250.0

In [34]:
sol.x

array([10.,  5.])

## 4. Problema de transporte 1
- **Referencia**: http://bdigital.unal.edu.co/5037/4/guillermojimenezlozano.2006_Parte1.pdf

Una  empresa tiene dos fábricas A y B.  En ellas  se fabrica un determinado  producto, a razón de 500  y 400 unidades por día respectivamente.  El producto  ha  de  ser distribuido posteriormente  a  tres  centros  C,  D  y  E,  que  requieren,  respectivamente,  200,  300  y  400  unidades.  Los  costos  de  transportar cada unidad del producto desde cada fábrica a cada centro distribuidor son los  indicados  en la tabla  siguiente: 

Factoría|C|D|E|Fabricación (Unidades)
:----|----|----|----|----
A|  50 u.m|60 u.m|10 u.m|500 u
B|  25 u.m|40 u.m|20 u.m|400 u
Demanda|200|300|400|

**¿De qué manera  deben  organizar  el transporte a fin de que los gastos sean mínimos?**



1. Identificar criterio
   
Minimizar el costo total de transporte de las fabricas a los centros 

2. Variables de control
* AC
* AD
* AE
* BC
* BD
* BE

3. Funcion de costo

$ f(AC, AD, AE, BC, BD, BE) = 50AC + 60AD + 10AE + 25BC+ 40BD+ 20BE $

4. Restricciones

Unidades de fabricacion de un determinado producto

$ AC + AD + AE \leq 500 $

$ BC + BD + BE \leq 400 $

Demanda de los centros de distribucion 

$ AC + BC = 200 $

$ AD + BD = 300 $

$ AE + BE = 400 $

$$ \min_{AC, AD, AE, BC, BD, BE} 50AC + 60AD + 10AE + 25BC+ 40BD+ 20BE $$
$$ \text {s.t.} $$
$$ AC + AD + AE \leq 500 $$
$$ BC + BD + BE \leq 400 $$
$$ AC + BC \geq 200 $$
$$ AD + BD \geq 300 $$
$$ AE + BE \geq 400 $$


In [74]:
import numpy as np
import scipy.optimize as opt

c = np.array([50, 60, 10, 25, 40, 20])

Aub = np.array([
    [1, 1, 1, 0, 0, 0], 
    [0, 0, 0, 1, 1, 1],
    [-1, 0, 0, -1, 0, 0],
    [0, -1, 0, 0, -1, 0],
    [0, 0, -1, 0, 0, -1]
   
])

bub = np.array([500, 400, -200, -300, -400])

sol = opt.linprog(c, Aub, bub,integrality=1)
sol.fun #costo total mínimo 

23000.0

El objetivo de este problema es determinar la mejor estrategia de inversión, dados diferentes tipos de bono, la máxima cantidad que puede ser invertida en cada bono, el porcentaje de retorno y los años de madurez. También hay una cantidad fija de dinero disponible ($\$750,000$). Por lo menos la mitad de este dinero debe ser invertido en bonos con 10 años o más para la madurez. Se puede invertir un máximo del $25\%$ de esta cantidad en cada bono. Finalmente, hay otra restricción que no permite usar más de $35\%$ en bonos de alto riesgo.

Existen seis (6) opciones de inversión con las letras correspondientes $A_i$

1. $A_1$:(Tasa de retorno=$8.65\%$; Años para la madurez=11, Riesgo=Bajo)
1. $A_2$:(Tasa de retorno=$9.50\%$; Años para la madurez=10, Riesgo=Alto)
1. $A_3$:(Tasa de retorno=$10.00\%$; Años para la madurez=6, Riesgo=Alto)
1. $A_4$:(Tasa de retorno=$8.75\%$; Años para la madurez=10, Riesgo=Bajo)
1. $A_5$:(Tasa de retorno=$9.25\%$; Años para la madurez=7, Riesgo=Alto)
1. $A_6$:(Tasa de retorno=$9.00\%$; Años para la madurez=13, Riesgo=Bajo)

Lo que se quiere entonces es maximizar el retorno que deja la inversión.

Este problema puede ser resuelto con programación lineal. Formalmente, puede ser descrito como:

$$\max_{A_1,A_2,...,A_6}\sum^{6}_{i=1} A_iR_i,$$

donde $A_i$ representa la cantidad invertida en la opción, y $R_i$ representa la tasa de retorno respectiva.

1. Identificar criterio

Maximizar el retorno de la inversión dado los riesgos, y los años de madurez, también los bonos

2. Variables de control
* A1
* A2
* A3
* A4
* A5
* A6
 
3. Funcion de costo

f(A1, A2, A3, A4, A5, A6) = 0.0865A1 + 0.0950A2 + 0.10A3 + 0.0875A4 + 0.0925A5 + 0.090A6

4. Restricciones

Cantidad fija

$ A1+A2+A3+A4+A5+A6 \leq 750000 $

Inversion minima con al menos 10 años

$ A1+A2+A4+A6 \geq 375000 $

inversion por bono 

$ A1 \leq 187500 $

$ A2 \leq 187500 $

$ A3 \leq 187500 $

$ A4 \leq 187500 $

$ A5 \leq 187500 $

$ A6 \leq 187500 $

bono alto riesgo

$ A2 + A3 + A5 \leq 262500 $

$$ \min_{x1,x2,x3,x4,x5, x6} 0.0865A1 + 0.0950A2 + 0.10A3 + 0.0875A4 + 0.0925A5 + 0.090A6 $$
$$ \text {s.t.} $$
$$ A1+A2+A3+A4+A5+A6 \leq 750000 $$
$$ A1+A2+A4+A6 \geq 375000$$
$$ A1 \leq 187500 $$
$$ A2 \leq 187500 $$
$$ A3 \leq 187500 $$
$$ A4 \leq 187500 $$
$$ A5 \leq 187500 $$
$$ A6 \leq 187500 $$
$$ A2 + A3 + A5 \leq 262500$$

   


In [59]:
import scipy.optimize as opt
import numpy as np 

Aub = np.array([
    [1,  1,  1,  1, 1, 1],
    [-1, -1,  0,  -1, 0 , -1],
    [1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 1],
    [0, 1, 1, 0, 1, 0]
])

bub = np.array([
    750000,
    -375000,
    187500,
    187500,
    187500,
    187500,
    187500,
    187500,
    262500

])

c = np.array([
    -0.0865,
    -0.0950,
    -0.10,
    -0.0875,
    -0.0925,
    -0.090
])


sol= opt.linprog(c,Aub,bub) 
sol.fun

-68887.5

In [61]:
sol.x

array([112500.,  75000., 187500., 187500.,      0., 187500.])

$ A05 $

Se quiere producir comida para gatos de la manera más barata, no obstante se debe también asegurar que se cumplan los datos requeridos de analisis nutricional. Por lo que se quiere variar la cantidad de cada ingrediente para cumplir con los estandares nutricionales. Los requisitos que se tienen es que en 100 gramos, se deben tener por lo menos 9 gramos de proteína y  7 gramos de grasa. Así mismo, no se debe tener más de 2.5 gramos de fibra y 0.5 gramos de sal.
2

Lo que se busca optimizar en este caso es la cantidad de productos que se debe utilizar en la comida de gato, minimizando el costo total.

1. Identificar criterio 

Se quiere minimizar el costo total de la comida de gato

2. Variables de control (Sobre que tengo el control?)

* Cantidad de pollo
* Cantidad de Carne
* Cantidad de Cordero
* Cantidad de Arroz
* Cantidad de Trigo
* Cantidad de Gel

3. funcion de costo
$ f(x1, x2, x3, x4, x5, x6) = 0.012x1 + 0.009x2 + 0.010x3 + 0.003x4 + 0.005x5 + 0.002x6 $

4. Restricciones

* Proteina
$ 0.10x1 + 0.20x2 + 0.15x3 + 0.00x4+ 0.04x5 + 0.00x6 \geq 9 $

* Grasa
$ 0.08x1 + 0.10x2 + 0.11x3 + 0.01x4 + 0.01x5 + 0.00x6 \geq 7 $

* Fibra 
$ 0.001x1 + 0.005x2 + 0.005x3 + 0.10x4 + 0.15x5 + 0.00x6 \leq 2.5 $

* Sal
$ 0.002x1 + 0.005x2 + 0.007x3 + 0.002x4 + 0.008x5 + 0.00x6 \leq 0.5 $

* Total
$ x1 + x2 + x3 + x4 + x5 + x6 = 100 $

$$ \min_{x1,x2,x3,x4,x5, x6} 0.012x1 + 0.009x2 + 0.010x3 + 0.003x4 + 0.005x5 + 0.002x6 $$
$$ \text {s.t.} $$
$$ 0.10x1 + 0.20x2 + 0.15x3 + 0.00x4+ 0.04x5 + 0.00x6 \geq 9 $$
$$0.08x1 + 0.10x2 + 0.11x3 + 0.01x4 + 0.01x5 + 0.00x6 \geq 7$$
$$0.001x1 + 0.005x2 + 0.005x3 + 0.10x4 + 0.15x5 + 0.00x6 \leq 2.5$$
$$0.002x1 + 0.005x2 + 0.007x3 + 0.002x4 + 0.008x5 + 0.00x6 \leq 0.5$$
$$ x1+x2+x3+x4+x5+x6 = 100$$
   

In [89]:
import scipy.optimize as opt
import numpy as np 

Aub = np.array([
    [-0.10,  -0.20,  -0.15,  0, -0.04, 0],
    [-0.08,  -0.10,  -0.11,  -0.01, -0.01,0],
    [0.001, 0.005, 0.005, 0.10, 0.15, 0],
    [0.002, 0.005, 0.007, 0.002, 0.008, 0]
])

bub = np.array([
    -9,
    -7,
    2.5,
    0.5

])

c = np.array([
    0.012,
    0.009,
    0.010,
    0.003,
    0.005,
    0.002
])

Aeq = np.array([
    [1,1,1,1,1,1]
])

beq = np.array([
    100
])

sol= opt.linprog(c,Aub,bub, Aeq, beq) 
sol.fun

0.69

In [91]:
sol.x

array([ 0., 70.,  0.,  0.,  0., 30.])

#### A05 ejercicio 2

La Comisión Federal de Electricidad (CFE) dispone de cuatro plantas de generación para satisfacer la demanda diaria eléctrica en cuatro ciudades, Guadalajara, León y Morelia. Las plantas 1, 2 y 3 pueden satisfacer 75, 50 y 60 millones de kW al día respectivamente. Las necesidades de las ciudades de Guadalajara, León y Morelia son de 60, 45 y 60 millones de Kw al día respectivamente.

Los costos asociados al envío de suministro energético por cada millón de kW entre cada planta y cada ciudad son los registrados en la siguiente tabla.

1. Identificar criterio
El criterio es minimizar el costo total de envío de suministro energético desde las plantas de generación hacia las ciudades de Guadalajara, León y Morelia.

2. Variables de control en cantidades de energía a plantas

* x11 : Desde planta 1 a GDL
* x12 : Desde planta 1 a León
* x13 : desde planta 1 a Morelina
* x21 : desde planta 2 a Gdl
* x22 : desde planta 2 a León
* x23 : desde planta 2 a Morelia
* x31 : desde planta 3 a GDL
* x32 : desde planta 3 a León
* x33 : desde planta 3 a Morelia

3. Función de costo

$ Total = 5x11 + 2x12 + 7x13 + 3x21 + 4x22 + 5x23 + 5x31 + 2x32 + 3x33 $

4. Restricciones

* Capacidad en plantas (en millones de kW)
  * Planta 1
    $ x11 + x12 + x13 \leq 75 $
  * Planta 2
    $ x21 + x22 + x23 \leq 50 $
  * Planta 3
    $ x31 + x32 + x33 \leq 60 $

* Demanda en las ciudades (en millones de kW)
  * GDL
    $ x11 + x21 + x31 = 60 $
  * León
    $ x12 + x22 + x32 = 45 $
  * Morelia
    $ x13 + x23 + x33 = 60 $
    
$$ \min_{x1,x2,x3,x4,x5, x6} 5x11 + 2x12 + 7x13 + 3x21 + 4x22 + 5x23 + 5x31 + 2x32 + 3x33 $$
$$ \text {s.t.} $$
$$ x11 + x12 + x13 \leq 75 $$
$$ x21 + x22 + x23 \leq 50$$
$$ x31 + x32 + x33 \leq 60$$
$$ x11 + x21 + x31 \geq 60$$
$$ x12 + x22 + x32 \geq 45$$
$$ x13 + x23 + x33 \geq 60$$

In [87]:
import numpy as np
import scipy.optimize as opt

c = np.array([5, 2, 7, 3, 4, 5, 5, 2, 3])

Aub = np.array([
    [1, 1, 1, 0, 0, 0, 0, 0, 0],  # Capacidad de planta 1 <= 75
    [0, 0, 0, 1, 1, 1, 0, 0, 0],  # Capacidad de planta 2 <= 50
    [0, 0, 0, 0, 0, 0, 1, 1, 1],  # Capacidad de planta 3 <= 60
    [-1, 0, 0, -1, 0, 0, -1, 0, 0],  # Demanda GDL >= 60
    [0, -1, 0, 0, -1, 0, 0, -1, 0],  # Demanda León >= 45
    [0, 0, -1, 0, 0, -1, 0, 0, -1]   # Demanda Morelia >= 60
])

bub = np.array([75, 50, 60, -60, -45, -60])

sol = opt.linprog(c, Aub, bub,integrality=1)
sol.fun #costo total mínimo 

470.0

In [85]:
sol.x #cantidad de energía desde cada planta a cada ciudad

array([10., 45.,  0., 50.,  0.,  0.,  0.,  0., 60.])

A06 Ejercicio 1.

Una carpintería local fabrica sillas, mesas, libreros y bases de cama. Hay dos empleados en esta carpintería: un empleado experimentado y un aprendiz. El aprendiz tarda aproximadamente 50% más tiempo que el carpintero experimentado en construir cualquier cosa, además de que tiene un desperdicio de alrededor de 20% de material. Los materiales y tiempos necesarios para construir algo se desglozan en la siguiente tabla:

Mesa = 3, 6

Silla = 1, 2

Libreros = 4, 5

Bases = 3, 5

Las mesas se venden en  9000, las sillas en  3000, los libreros en  10000, y las bases de cama en  9000. Suponiendo una jornada de 40 horas a la semana y que tienen 100 unidades de madera, ¿qué les conviene construir durante una semana para maximizar su ganancia?

* ¿Cuántas horas trabaja cada quién?
  
* ¿Cuánto material se usa?
  
* ¿Cuál se el ingreso total si se vende todo lo fabricado?

1. Identificar el criterio
   
Se busca maximizar la ganancia 

3. Variables de control
   
* Cantidad de mesas del empleado (x1)
* Cantidad de sillas del empleado (x2)
* Cantidad de libreros del empleado (x3)
* Cantidad de bases de cama del empleado (x4)
* Cantidad de mesas del aprendiz (y1)
* Cantidad de sillas del aprendiz (y2)
* Cantidad de libreros del aprendiz (y3)
* Cantidad de bases de cama del aprendiz (y4)
  
3. funcion de costo
   
  $ f(x1, x2, x3, x4, y1, y2, y3, y4) = 9000x1+ 9000y1 + 3000x2+3000y2 + 10000x3+10000y3 + 9000x4+ 9000y4 $

4. Restricciones

Tiempo experimentado

$ 3x1 + 1x2 + 4x3 + 3x4 \leq 40 $

Tiempo aprendiz 

$ 4.5y1 + 1.5y2 + 6y3 + 4.5y4 \leq 40 $

Material 

$ 6x1 + 7.2y1 + 2x2+ 2.4y2 + 5x3 + 6y3 + 5x4+ 6y4 \leq 100 $

$$ \min_{x1,x2,x3,x4,y1,y2,y3,y4} -9000x1-9000y1-3000x2-3000y2-10000x3-10000y3-9000x4-9000y4 $$
$$ \text {s.t.} $$
$$3x1+1x2+4x3+3x4 \leq 40$$
$$4.5y1+1.5y2+6y3+4.5y4 \leq 40$$
$$6x1+7.2y1+2x2+2.4y2+5x3+6y3+5x4+6y4 \leq 100$$

In [35]:
import scipy.optimize as opt
import numpy as np

Aub = np.array([
    [3,  0,  1,  0,  4, 0, 3, 0],
    [0, 4.5, 0, 1.5, 0, 6, 0, 4.5],
    [6, 7.2, 2, 2.4, 5, 6, 5, 6]
])

bub = np.array([
    40,
    40,
    100

])

c = np.array([
    -9000,
    -9000,
    -3000,
    -3000,
    -10000,
    -10000,
    -9000,
    -9000
])

sol= opt.linprog(c,Aub,bub,integrality=1) 
sol.fun #el dinero de todo lo fabricado 

-176000.0

In [37]:
sol.x

array([ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00, -9.47390314e-15,
        9.00000000e+00,  2.00000000e+00,  1.00000000e+00,  6.00000000e+00])

In [39]:
Aub @ sol.x  

array([ 40.,  39., 100.])

2. La carpintería recibió una orden  por 3 combos de mesa + 6 sillas.
* ¿Se puede cumplir la orden? Sí 
* Si sí, ¿qué es lo que tienen que fabricar en el resto del tiempo y con el resto del material para maximizar su ganancia?
* ¿Cuántas horas trabaja cada quién?
* ¿Cuánto material se usa?
* ¿Cuál es el nuevo ingreso total?

4. Restricciones extras
   
Mesas

$ x1+y1 \geq 3 $

Sillas

$ x2+y2 \geq 18 $

$$ \min_{x1,x2,x3,x4,y1,y2,y3,y4} -9000x1-9000y1-3000x2-3000y2-10000x3-10000y3-9000x4-9000y4 $$
$$ \text {s.t.} $$
$$3x1+1x2+4x3+3x4 \leq 40$$
$$4.5y1+1.5y2+6y3+4.5y4 \leq 40$$
$$6x1+7.2y1+2x2+2.4y2+5x3+6y3+5x4+6y4 \leq 100$$
$$ x1+y1 \geq 3 $$
$$ x2+y2 \geq 18 $$

In [74]:
import scipy.optimize as opt
import numpy as np


c = np.array([-9000, -9000, -3000, -3000, -10000, -10000, -9000, -9000])

Aub = np.array([
    [3, 0, 1, 0, 4, 0, 3, 0],     
    [0, 4.5, 0, 1.5, 0, 6, 0, 4.5], 
    [6, 7.2, 2, 2.4, 5, 6, 5, 6],
    [0, 0, -1, -1, 0, 0, 0, 0],
    [-1, -1, 0, 0, 0, 0, 0, 0] 
])

bub = np.array([
    40,
    40,
    100,
    -18,
    -3
])


sol = opt.linprog(c,Aub,bub,integrality=1) 
sol.fun  #la ganancia total


-161000.0

In [76]:
sol.x   #esto es lo que tienen que fabricar para maximizar ganancias 

array([ 3.,  0., 18.,  0.,  3.,  5.,  0.,  0.])

In [78]:
Aub @ sol.x  #tiempo de ambos y el material

array([ 39.,  30.,  99., -18.,  -3.])